<?php

namespace CategoriesBundle\Repository;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllParents()
    {
        $qb = $this->createQueryBuilder('p');

        $qb->select('p')
            ->from('CategoriesBundle:Categories', 'c')
            ->where('p.parent is null');

        return $qb->getQuery()->getResult();
    }
}
