<?php

namespace CategoriesBundle\Repository;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCategories()
    {
        $qb = $this->createQueryBuilder('p');

        return $qb;
    }

    public function findAllNotNUll()
    {
        $qb = $this->createQueryBuilder('p');

        $qb->select('p')
            ->from('CategoriesBundle:Categories', 'c')
            ->where($qb->expr()->isNull('p.isParent'))
            ->orWhere($qb->expr()->eq('p.isParent', 'false'));

        return $qb->getQuery()->getResult();
    }
}
