<?php

namespace AccountBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TransactionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionsRepository extends EntityRepository
{
  public function findAllByMonth($month)
  {
    return $this->getEntityManager()
      ->createQuery(
        "SELECT p FROM AccountBundle:Transactions p WHERE MONTH(p.createAt) = $month ORDER BY p.createAt ASC"
      )
      ->getResult();
  }
}
