<?php

namespace ImporterBundle\Repository;

/**
 * ImportedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportedRepository extends \Doctrine\ORM\EntityRepository
{
}
